chore: update getPage to use apollo
vuestorefront/shopify pull request #216
Opened 2022-02-10 06:10 UTC by jeffpdotone

Closes #198

## Description
This is an update to use the graphql query page through the apollo client

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-02-10 09:03 UTC, Mateuszpietrusinski requested changes
Requires adjustments

2022-02-10 09:03 UTC, Mateuszpietrusinski commented on packages/apollo/src/library.ts
> +}
(https://blog.logrocket.com/types-vs-interfaces-in-typescript/)
Interfaces are basically a way to describe data shapes, for example, an object.

Type is a definition of a type of data, for example, a union, primitive, intersection, tuple, or any other type.

2022-02-10 09:03 UTC, Mateuszpietrusinski commented on packages/composables/src/useContent/index.ts
> +        return response.data.page;
Optional chaining in case of errors
```suggestion
        return response?.data?.page;
```

2022-02-11 08:35 UTC, jeffpdotone commented on .editorconfig
> +insert_final_newline = false
so far it's aligned with prettier & eslint

2022-02-23 08:55 UTC, Mateuszpietrusinski requested changes
Some warnings are in the pr, check them. One question, why do you prefer to use default export instead of direct export/import? + one improvment

2022-02-23 08:55 UTC, Mateuszpietrusinski commented on packages/apollo/__tests__/searchProduct.spec.ts
> +        query: expect.any(Object),
In long term the query should be provided here

2022-02-23 08:55 UTC, Mateuszpietrusinski commented on packages/apollo/src/api/getPage.ts
> +  return response ?? null
allocation is redundant 
```suggestion
  return await context.client.apolloClient.query<QueryRoot, QueryRootPageArgs>({
    query: page.query,
    variables: page.variables
  }) ?? null
```

2022-02-23 08:55 UTC, Mateuszpietrusinski commented on packages/apollo/src/types/ExtendQueryContext.ts
> +export default interface ExtendQueryContext {
Use without default
```suggestion
export interface ExtendQueryContext {
```

2022-02-23 08:55 UTC, Mateuszpietrusinski commented on packages/apollo/src/library.ts
> +import ExtendQueryContext from "./types/ExtendQueryContext"
those interfaces can be imported from destructuration instead as default

2022-02-23 08:55 UTC, Mateuszpietrusinski commented on packages/apollo/src/types/ShopifyApolloClient.ts
> +export default interface ShopifyApolloClient { apolloClient: ReturnType<typeof createShopifyApollo> }
same as above

2022-02-23 08:55 UTC, Mateuszpietrusinski commented on packages/apollo/src/types/ShopifyApolloSettings.ts
> +export default interface ShopifyApolloSettings {
same as above

2022-02-23 08:55 UTC, Mateuszpietrusinski commented on packages/apollo/src/types/getPage/GetPageParams.ts
> +export default interface GetPageParams {
same as above

2022-02-23 09:10 UTC, jeffpdotone commented on packages/apollo/__tests__/searchProduct.spec.ts
> +        query: expect.any(Object),
Will provide this in the next unit tests

2022-02-23 09:17 UTC, Mateuszpietrusinski approved these changes
small questions

2022-02-23 09:17 UTC, Mateuszpietrusinski commented on packages/api-client/src/api/customerMutations/buildQueries.ts
> +const addressesQuery: (pages: number, token: string, context) => any = (_pages, token, context): any => {
Can we add the returning type here?

2022-02-23 09:17 UTC, Mateuszpietrusinski commented on packages/api-client/src/api/fetchOrders/index.ts
> +export default function fetchOrders(context, params) {
Just being curious are we now passing customQuery in params?

2022-02-23 09:29 UTC, jeffpdotone commented on packages/api-client/src/api/fetchOrders/index.ts
> +export default function fetchOrders(context, params) {
This is are from old fetchOrders and doesn't implement yet the customQuery.

2022-02-23 09:42 UTC, merged