chore: update getCategory to use apollo
vuestorefront/shopify pull request #217
Opened 2022-02-11 15:59 UTC by jeffpdotone

Closes #192, #190

## Description
This is an update to use the graphql query collection through the apollo client

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-02-24 10:01 UTC, Mateuszpietrusinski requested changes
check comments and contact me in case of questions

2022-02-24 10:01 UTC, Mateuszpietrusinski commented on packages/composables/src/useFacet/index.ts
> +    result.products = convertProductsGqlToLocal(result.products as ProductConnection)
in the future we should move mappings maybe to backend cuz its really unperformant

2022-02-24 10:01 UTC, Mateuszpietrusinski commented on packages/composables/src/useFacet/index.ts
> +      products: enhanceProduct(result.products),
same here

2022-02-25 08:43 UTC, Mateuszpietrusinski requested changes
I didn't check the tests yet, maybe Viral can look at them

2022-02-25 08:43 UTC, Mateuszpietrusinski commented on packages/apollo/src/helpers/mapFacetToProductFilter.ts
> +  return result
Redundant variable
```suggestion
 return  {
    ...getPriceFilters()
  }
```

2022-02-25 08:43 UTC, Mateuszpietrusinski commented on packages/apollo/src/helpers/mapFacetToProductFilter.ts
> +    }
```suggestion
   if (!filters.min || !filters.max) {
      return {};
    }
    
    return {
      price: {
        ...(filters.min && { min: parseFloat(filters.min) }),
        ...(filters.max && { max: parseFloat(filters.max) })
      }
    };
```

2022-02-25 08:43 UTC, Mateuszpietrusinski commented on packages/apollo/src/helpers/mapFacetToProductFilter.ts
> +    }
Is known as guard block. It is better suited to return/throw exception early if something went wrong (wrong parameter or invalid state)

2022-02-25 11:30 UTC, jeffpdotone commented on packages/apollo/src/helpers/mapFacetToProductFilter.ts
> +    }
should be && if there's no min and max return empty object.

2022-03-01 09:09 UTC, Mateuszpietrusinski requested changes
Small comments and one critical

2022-03-01 09:09 UTC, Mateuszpietrusinski commented on packages/apollo/__tests__/getCollection.spec.ts
> +    const mockContext = createMockContext()
you can make desctructurization here
```suggestion
    const { context: mockContext, extendQuery: mockExtendQuery } = createMockContext()
```

2022-03-01 09:09 UTC, Mateuszpietrusinski commented on packages/apollo/__tests__/getCollection.spec.ts
> +    mockContext.extendQuery.mockImplementationOnce(() => ({ collection: { query: 'test-quert', variables: expectedVariables } }));
```suggestion
   mockExtendQuery.mockImplementationOnce(() => ({ collection: { query: 'test-quert', variables: expectedVariables } }));
```

2022-03-01 09:09 UTC, Mateuszpietrusinski commented on packages/apollo/__tests__/getCollection.spec.ts
> +    await getCollection(mockContext.context, params, customQuery)
```suggestion
    await getCollection(mockContext, params, customQuery)
```

2022-03-01 09:09 UTC, Mateuszpietrusinski commented on packages/apollo/__tests__/getCollection.spec.ts
> +    expect(mockContext.extendQuery).toHaveBeenCalledWith(customQuery, {
```suggestion
    expect(mockExtendQuery).toHaveBeenCalledWith(customQuery, {
```

2022-03-01 09:09 UTC, Mateuszpietrusinski commented on packages/apollo/__tests__/getCollection.spec.ts
>          query: expect.any(Object),
just wondering can we somehow check the query its better to verify is everything here is as suppose to be

2022-03-01 09:09 UTC, Mateuszpietrusinski commented on packages/apollo/__tests__/getCollection.spec.ts
> +    const mockContext = createMockContext()
same as above

2022-03-01 09:09 UTC, Mateuszpietrusinski commented on packages/apollo/__tests__/getCollection.spec.ts
> +    mockContext.extendQuery.mockImplementationOnce(() => ({ collection: { query: 'test-quert', variables: mappedVariables } }));
same as above

2022-03-01 09:09 UTC, Mateuszpietrusinski commented on packages/apollo/__tests__/getPage.spec.ts
> +const mockContext = createMockContext()
same as above

2022-03-01 09:09 UTC, Mateuszpietrusinski commented on packages/apollo/__tests__/searchProduct.spec.ts
> +    mockContext.extendQuery.mockImplementationOnce(() => ({ products: { query: 'test-products-query', variables: expectedVariables }}))
same as above

2022-03-01 09:09 UTC, Mateuszpietrusinski commented on packages/apollo/src/api/getCollection.ts
> +    filters: mapFacetToProductFilter(params.filters)
We can destructure params and use them directly `{categorySlug, perPage, filters}`

2022-03-01 09:09 UTC, Mateuszpietrusinski commented on packages/apollo/src/api/searchProduct.ts
> +const defaultQuery = gql`
IMO it should have the previous name cuz it is located in the node closure. I know that getCollection has the same variable name in the same closure it will affect the problem.

2022-03-07 05:14 UTC, aureate-labs-team approved these changes

2022-03-07 11:54 UTC, aureate-labs-team commented
@jeffpdotone Please resolve conflicts

2022-03-07 12:56 UTC, Mateuszpietrusinski approved these changes
There are some warnings at the bottom of pr please look at them if they are not related to this pr please create a new one and resolve them.

2022-03-08 00:18 UTC, merged