Cart Drawer: coupon feature
vuestorefront/shopify pull request #243
Opened 2022-03-03 13:21 UTC by aureate-labs-team

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-03-03 13:56 UTC, jeffpdotone requested changes

2022-03-03 13:56 UTC, jeffpdotone commented on packages/api-client/src/api/applyCartCoupon/index.ts
> +          mutation: print(DEFAULT_MUTATION as any),
we can remove the print and any here. please refer to this PR #217

2022-03-03 13:56 UTC, jeffpdotone commented on packages/api-client/src/api/applyCartCoupon/index.ts
> +    mutation: gql(checkoutDiscountCodeApplyV2.mutation) as any,
can remove **gql** and **as any** here

2022-03-03 13:56 UTC, jeffpdotone commented on packages/api-client/src/api/cartMutations/buildMutations.ts
> +  const input = context.client.graphQLClient.variable('input', 'CartInput!');
can we use apolloClient here instead?

2022-03-03 13:56 UTC, jeffpdotone commented on packages/api-client/src/api/removeCartCoupon/index.ts
> +          mutation: print(DEFAULT_MUTATION as any),
same as above remove print and as any

2022-03-03 13:56 UTC, jeffpdotone commented on packages/api-client/src/api/removeCartCoupon/index.ts
> +    mutation: gql(checkoutDiscountCodeRemove.mutation) as any,
remove gql and as any

2022-03-04 05:36 UTC, aureate-labs-team commented on packages/api-client/src/api/removeCartCoupon/index.ts
> +    mutation: gql(checkoutDiscountCodeRemove.mutation) as any,
Chages applied

2022-03-04 05:36 UTC, aureate-labs-team commented on packages/api-client/src/api/removeCartCoupon/index.ts
> +          mutation: print(DEFAULT_MUTATION as any),
Changes applied

2022-03-04 05:36 UTC, aureate-labs-team commented on packages/api-client/src/api/applyCartCoupon/index.ts
> +    mutation: gql(checkoutDiscountCodeApplyV2.mutation) as any,
Changes applied

2022-03-04 05:36 UTC, aureate-labs-team commented on packages/api-client/src/api/applyCartCoupon/index.ts
> +          mutation: print(DEFAULT_MUTATION as any),
Changes applied

2022-03-04 06:30 UTC, aureate-labs-team commented on packages/api-client/src/api/cartMutations/buildMutations.ts
> +  const input = context.client.graphQLClient.variable('input', 'CartInput!');
It was because we were trying to initiate a cart instead of checkout. But there were many impacted areas. So reverting it. Will take it later on

2022-03-04 14:04 UTC, jeffpdotone approved these changes

2022-03-04 14:05 UTC, jeffpdotone requested changes
let's update the versions when we release it to production/public

2022-03-08 00:51 UTC, jeffpdotone requested changes

2022-03-08 00:51 UTC, jeffpdotone commented on packages/api-client/src/api/applyCartCoupon/index.ts
> +export default async function applyCoupon(context, params, _customQuery?: CustomQuery) {
We also want to move away from export default, instead use the export async function straight and update the import syntax too.

2022-03-08 00:51 UTC, jeffpdotone commented on packages/api-client/src/api/applyCartCoupon/index.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
if we have unused variables please remove those.

2022-03-08 00:51 UTC, jeffpdotone commented on packages/api-client/src/api/getProduct/index.ts
>  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Same here please remove what we have unused and drop this comment.

2022-03-08 00:51 UTC, jeffpdotone commented on packages/api-client/src/api/removeCartCoupon/index.ts
> +export default async function removeCoupon(context, params, _customQuery?: CustomQuery) {
Same thing remove default and update import syntax

2022-03-08 00:51 UTC, jeffpdotone commented on packages/api-client/src/api/removeCartCoupon/index.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
remove unused and drop this eslint-disable.

2022-03-08 00:51 UTC, jeffpdotone commented on packages/composables/package.json
> +  "version": "1.0.19",
remove any version update on this PR not related to this we'll update version on our publish

2022-03-08 00:51 UTC, jeffpdotone commented on packages/composables/src/getters/cartGetters.ts
> +  if (cart && cart.discountApplications && cart.discountApplications.length > 0) {
Can we use optional chaining here?

2022-03-08 00:51 UTC, jeffpdotone commented on packages/composables/src/getters/cartGetters.ts
> +  if (cart && cart.checkoutUserErrors && cart.checkoutUserErrors.length <= 0) {
same here optional chaining?

2022-03-08 05:50 UTC, aureate-labs-team commented on packages/api-client/src/api/applyCartCoupon/index.ts
> +export default async function applyCoupon(context, params, _customQuery?: CustomQuery) {
Suggestion implemented

2022-03-08 05:50 UTC, aureate-labs-team commented on packages/api-client/src/api/applyCartCoupon/index.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
Changes done

2022-03-08 07:03 UTC, aureate-labs-team commented on packages/api-client/src/api/getProduct/index.ts
>  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Resolved

2022-03-08 07:09 UTC, aureate-labs-team commented on packages/api-client/src/api/removeCartCoupon/index.ts
> +export default async function removeCoupon(context, params, _customQuery?: CustomQuery) {
Resolved

2022-03-09 07:43 UTC, jeffpdotone requested changes

2022-03-09 11:29 UTC, jeffpdotone approved these changes

2022-03-10 12:52 UTC, merged