Adjustments with use cart composable methods (createCart & Checkout)
vuestorefront/shopify pull request #246
Opened 2022-03-04 12:38 UTC by aureate-labs-team

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-03-04 14:06 UTC, jeffpdotone requested changes
lets update version when we publish it to main

2022-03-10 13:07 UTC, jeffpdotone commented
Please fix conflicts

2022-03-10 13:23 UTC, jeffpdotone requested changes

2022-03-10 13:23 UTC, jeffpdotone commented on packages/api-client/src/api/createCart/index.ts
> +    checkoutCreate(input:$input){
Aren't we updating to cartCreate?

2022-03-10 13:23 UTC, jeffpdotone commented on packages/theme/layouts/default.vue
> +    LazyHydrate,
Remove the duplicate please. :)

2022-03-10 13:24 UTC, aureate-labs-team commented on packages/api-client/src/api/createCart/index.ts
> +    checkoutCreate(input:$input){
Not now. As its impacted area is high. Right now, replaced Shopify buy deps with Appolo client

2022-03-10 13:27 UTC, jeffpdotone approved these changes

2022-03-10 13:27 UTC, merged