refactor: adjustments with checkout, addtocart, removefromcart, updatecart methods for  coupon code
vuestorefront/shopify pull request #257
Opened 2022-03-14 13:27 UTC by aureate-labs-team

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-03-15 08:11 UTC, Mateuszpietrusinski requested changes
Some questions and adjustment needed

2022-03-15 08:11 UTC, Mateuszpietrusinski commented on packages/api-client/src/api/getProduct/index.ts
> +      country: curLocaleCode === "en" ? "US" : (curLocaleCode).toUpperCase(),
This is a bigger discussion on how to handle correctly the countries. We use configuration for i18n. For example:
```
{
  'en-US': ...something,
  'en-UK': ...something,
  'en-AU': ...something
}

Then you need to take the country from the code or maybe the i18n library somehow exposes the current country base on that format. Its better becouse we are not forced to hardcode the country like here

2022-03-15 08:11 UTC, Mateuszpietrusinski commented on packages/composables/src/getters/cartGetters.ts
> +  return cart.discountApplications[0].code;
We are expecting from that function to return `string` not `void`, after the changes if discount doesn't exist we are not returning any value

2022-03-15 08:11 UTC, Mateuszpietrusinski commented on packages/theme/components/CartSidebar.vue
> +                :regular="$n(totals.subtotal * totalDiscount.percentage/ (100 - totalDiscount.percentage), 'currency')"/>
this if is big maybe we can move the logic to the script part and here just return the value

2022-03-15 08:11 UTC, Mateuszpietrusinski commented on packages/theme/pages/articles/_handle.vue
> +        console.log('contents::', article.value)
should we just console log that value?

2022-03-16 07:13 UTC, aureate-labs-team commented on packages/api-client/src/api/getProduct/index.ts
> +      country: curLocaleCode === "en" ? "US" : (curLocaleCode).toUpperCase(),
Will be resolved by PR #262

2022-03-16 07:13 UTC, aureate-labs-team commented on packages/composables/src/getters/cartGetters.ts
> +  return cart.discountApplications[0].code;
Will be resolved by PR #262

2022-03-16 07:14 UTC, aureate-labs-team commented on packages/theme/components/CartSidebar.vue
> +                :regular="$n(totals.subtotal * totalDiscount.percentage/ (100 - totalDiscount.percentage), 'currency')"/>
It will be resolved by PR #262

2022-03-16 07:14 UTC, aureate-labs-team commented on packages/theme/pages/articles/_handle.vue
> +        console.log('contents::', article.value)
It will be resolved by PR #262

2022-03-25 08:25 UTC, jeffpdotone approved these changes

2022-03-25 09:17 UTC, merged