Refactor: adjustments with get country method
vuestorefront/shopify pull request #262
Opened 2022-03-16 06:27 UTC by aureate-labs-team

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-03-24 11:56 UTC, jeffpdotone commented on packages/composables/src/getters/cartGetters.ts
> +export const getCartItemAttributes = (product: LineItem) => {
Let's refactor this one too moving away from using getters and directly using the raw response.

2022-03-24 11:59 UTC, jeffpdotone commented on packages/composables/src/useCart/index.ts
> +    const APP = context.$shopify.config.app;
please use camelCase here to be consistent.

2022-03-24 13:02 UTC, aureate-labs-team commented on packages/composables/src/getters/cartGetters.ts
> +export const getCartItemAttributes = (product: LineItem) => {
I'll create a new task for this. As right now it's using the formatSelectedAttributeList() method, which is also used by another getter method getVariantByAttributes() is using it. So keep it as it is for now. will be refactor in next PR :)

2022-03-25 08:29 UTC, jeffpdotone requested changes
Please add unit tests for the methods being modified here. Can be just a happy path of a function been called with correct parameters.

2022-03-28 04:09 UTC, jeffpdotone commented
Please resolve conflicts.

2022-03-30 13:06 UTC, merged