fix: blog list issues
vuestorefront/shopify pull request #263
Opened 2022-03-16 06:40 UTC by jeffpdotone

This is a follow up changes for listing articles to fix certain issues.

2022-03-16 07:12 UTC, aureate-labs-team requested changes

2022-03-16 07:12 UTC, aureate-labs-team commented on packages/theme/components/AppHeader.vue
> +            :link="menu.handle.includes('/blogs') ? menu.handle : localePath('/c/' + menu.handle)"
Can we make the **blogs** middle-slug controllable by the customer by reading it from the public configuration/ENV?

2022-03-18 07:36 UTC, Mateuszpietrusinski requested changes
Im thinking about value of that check 
```
context.config?.routes?.blogs ?? '/blogs'
```
If we have a default set by runtime config do we need to check each time is it there? This should be a requirement if someone wants to use Blog functionality. Also please add that to documentation. The documentation should be included here. I saw many changes but no unit tests please also cover parts that need that.

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/components/AppHeader.vue
> +    const getMenuPath = (menu) => menu.handle.indexOf(context.$config?.blogsRoute) === 0 ? menu.handle : '/c/' + menu.handle
I'm not sure about that function. Maybe we can return an configuration route object instead of string

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/components/SearchResults.vue
> +                    )
Same as above this thing is really unreadable and if that's possible maybe we can remove getters and use just raw response https://router.vuejs.org/guide/essentials/named-routes.html

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/components/SearchResults.vue
> +                          )}/${productGetters.getSlug(product)}`
same as above

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/components/SearchResults.vue
> +                  )
same as above

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/components/SearchResults.vue
> +                      )
same as above

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/components/SearchResults.vue
> +              class="results--desktop desktop-only"
Can we have same html for Desktop & mobile? maybe we can handle changes by css?

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/components/SearchResults.vue
> +              hide-text=""
unnecessary properties

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/components/SearchResults.vue
> +                    localePath(`/articles/${article.handle}?id=${article.id}`)
same its better to use named routes later on its easier to maintain them https://router.vuejs.org/guide/essentials/named-routes.html

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/components/SearchResults.vue
> +                  localePath(`/articles/${article.handle}?id=${article.id}`)
same as above

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/components/SearchResults.vue
> +                  :image="articleGetters.getImage(article)"
We are trying to not use getters anymore they are unperformant. Use just raw respnse.

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/components/SearchResults.vue
> +                :image="articleGetters.getImage(article)"
same as above

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/components/SearchResults.vue
> +                    articleGetters.getPublishedAt(article)
same here

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/middleware.config.js
> +          articles: process.env.ARTICLES_ROUTE
Why we are putting those keys into environmental variables will they be different base on the environment?

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/nuxt.config.js
> +    articlesRoute: process.env.ARTICLES_ROUTE || '/articles'
From my perspective, if you need to have those keys in routimeConfg its enough to set string value here.

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/nuxt.config.js
> +  plugins: ['~/plugins/scrollToTop.client.js'],
Are we using that plugin?

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/nuxt.config.js
> +        return route;
I believe all this code will be generated based on the directory by nuxt

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/pages/articles/_handle.vue
> +        <img :src="articleGetters.getImage(article)" />
please use raw link instead of getters

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/pages/articles/_handle.vue
> +<script>
why are you deleting lang ts? What was the purpose?

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/pages/blogs/_handle.vue
> +      return `${context.$config?.articlesRoute ?? '/articles'}/${article.handle}?id=${article.id}`
same can we use https://router.vuejs.org/guide/essentials/named-routes.html

2022-03-18 07:36 UTC, Mateuszpietrusinski commented on packages/theme/pages/blogs/index.vue
> +        router.push(`${blogsRoute}/${content?.value?.[0]?.handle}`)
same here https://router.vuejs.org/guide/essentials/named-routes.html

2022-03-18 11:32 UTC, jeffpdotone commented on packages/theme/nuxt.config.js
> +        return route;
Yes this will be generated as the directory but will be replace by whatever they've set in the config or environment variables

2022-03-23 07:11 UTC, Frodigo requested changes
Hi @jeffpdotone, I left some comments. 

In addition, please fix all issues reported by the static code analysis tool. 

Thanks,
Marcin

2022-03-23 07:11 UTC, Frodigo commented on packages/apollo/src/api/getBlogs.ts
> +        link: `${context.config?.routes?.blogs ?? '/blogs'}/${edge?.node?.handle}`
As I mentioned before, consider to set default config value.

2022-03-23 07:11 UTC, Frodigo commented on packages/apollo/src/api/search.ts
> +  const searchQuery = gql`
Please export this query to separate file.

2022-03-23 07:11 UTC, Frodigo commented on packages/apollo/src/api/getBlog.ts
> +export async function getBlog(context: ShopifyApolloContext, params: QueryRootBlogArgs, customQuery?: CustomQuery) {
Please add return type for this function.

2022-03-23 07:11 UTC, Frodigo commented on packages/apollo/src/api/getBlogs.ts
> +export async function getBlogs(context: ShopifyApolloContext, params: QueryRootBlogsArgs, customQuery?: CustomQuery) {
Please add return type for this function.

2022-03-23 07:11 UTC, Frodigo commented on packages/composables/src/useContent/index.ts
> +          if (response?.error) throw response.error
What is the case when response is null or undefined?

2022-03-23 07:11 UTC, Frodigo commented on packages/theme/components/SearchResults.vue
> +            (products && products.length > 0) ||
Can you create a computed based on those conditions?

2022-03-23 07:11 UTC, Frodigo commented on packages/theme/composables/useUiState.ts
> +  articlesPerPage: '5'
This should come from global config.

2022-03-23 07:11 UTC, Frodigo commented on packages/theme/middleware.config.js
> +          blogs: '/ba',
`ba` and `aa` names are not understandable for humans.

2022-03-23 08:37 UTC, jeffpdotone commented on docs/guide/configuration.md
> +          blogs: '/blogs',
This is actually coming from the Shopify structure they have `blogs` acting as parent or category for `articles`

2022-03-23 08:38 UTC, jeffpdotone commented on packages/apollo/src/api/getArticles.ts
> +        link: `${context.config?.routes?.blogs ?? '/blogs'}/${edge?.node?.blog?.handle}/${edge?.node?.handle}`,
There is one already will remove this one.

2022-03-23 08:59 UTC, WojtekTheWebDev reviewed
good job @jeffpdotone! I added few suggestions + please take a look at the comments made by @Frodigo and @Mateuszpietrusinski, they had also few really good suggestions

2022-03-23 08:59 UTC, WojtekTheWebDev commented on packages/theme/components/AppHeader.vue
> +      }
```suggestion
      } 
      return { name: 'category', params: { slug_1: menu.handle } };
```

2022-03-23 08:59 UTC, WojtekTheWebDev commented on packages/theme/modules/cms/pages/articles/_handle.vue
> +import { useContent, articleGetters, ContentType } from '@vue-storefront/shopify';
Do you need `articleGetters`? I don't see that it was used here. If you're using it here, try to use raw response instead.

2022-03-23 08:59 UTC, WojtekTheWebDev commented on packages/theme/modules/cms/pages/blogs/_handle.vue
> +import { useContent, articleGetters, ContentType } from '@vue-storefront/shopify';
Try to refactor the page component to use raw data instead of `articleGetters`

2022-03-23 09:27 UTC, jeffpdotone commented
> Hi @jeffpdotone, I left some comments.
> 
> In addition, please fix all issues reported by the static code analysis tool.
> 
> Thanks, Marcin

We do have separate task for this coming along.

2022-03-23 09:39 UTC, jeffpdotone commented on packages/composables/src/useContent/index.ts
> +          if (response?.error) throw response.error
I have updated this and added a catch. In some cases, it doesn't get a response when the network call fails for some reason.

2022-03-23 09:40 UTC, jeffpdotone commented on packages/theme/composables/useUiState.ts
> +  articlesPerPage: '5'
Can you elaborate on this one? This is per se a uiState why decided it here. :)

2022-03-24 11:42 UTC, Frodigo commented on packages/theme/helpers/utils.ts
> +  const monthsArray = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
How about internationalization?

2022-03-24 15:44 UTC, jeffpdotone commented on packages/theme/helpers/utils.ts
> +  const monthsArray = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
I'll take this to another account/task.

2022-03-25 08:52 UTC, jeffpdotone commented on packages/theme/components/SearchResults.vue
> +              class="results--desktop desktop-only"
I'll create another card for this.

2022-03-25 09:23 UTC, aureate-labs-team approved these changes

2022-03-25 09:37 UTC, merged