refactor(sign in): removed shopify buy deps from signin api
vuestorefront/shopify pull request #309
Opened 2022-04-07 06:27 UTC by aureate-labs-team

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-07 07:04 UTC, jeffpdotone requested changes
can we rebased this I think there's too many unrelated changes to the topic.

2022-04-07 07:04 UTC, jeffpdotone commented on packages/theme/components/SearchResults.vue
> +                      :link="localePath(
Same here please use the route object I think it's already inside that function.

2022-04-07 07:04 UTC, jeffpdotone commented on packages/theme/components/SearchResults.vue
> +                  `/p/${productGetters.getId(product)}/${productGetters.getSlug(
route object

2022-04-07 07:04 UTC, jeffpdotone commented on packages/theme/components/SearchResults.vue
> +                      `/p/${productGetters.getId(product)}/${productGetters.getSlug(
route object

2022-04-07 07:04 UTC, jeffpdotone commented on packages/theme/components/SearchResults.vue
> +    // const getProductLink = (product) => {
I am not sure why this getting commented?

2022-04-07 10:16 UTC, aureate-labs-team commented on docs/guide/checkout.md
> +    const { slug } = route?.value?.params;
Yeah, it's giving the value as an object.

2022-04-08 05:08 UTC, aureate-labs-team commented on packages/theme/components/AppFooter.vue
> +    <SfFooterColumn title="Social">
Resolved in #308

2022-04-08 05:09 UTC, aureate-labs-team commented on packages/theme/components/AppFooter.vue
> +  margin-bottom: 3.75rem;
Resolved in #308

2022-04-08 05:10 UTC, aureate-labs-team commented on packages/theme/components/SearchResults.vue
> +                    `/p/${productGetters.getId(product)}/${productGetters.getSlug(
Resolved in #308

2022-04-08 05:10 UTC, aureate-labs-team commented on packages/theme/components/SearchResults.vue
> +                      :link="localePath(
Resolved in #308

2022-04-08 05:10 UTC, aureate-labs-team commented on packages/theme/components/SearchResults.vue
> +                  `/p/${productGetters.getId(product)}/${productGetters.getSlug(
Resolved in #308

2022-04-08 05:10 UTC, aureate-labs-team commented on packages/theme/components/SearchResults.vue
> +                      `/p/${productGetters.getId(product)}/${productGetters.getSlug(
Resolved in #308

2022-04-08 05:12 UTC, aureate-labs-team commented on packages/theme/components/SearchResults.vue
> +    // const getProductLink = (product) => {
Reverted. There was a condition bug so that the URL was not generating. It was fixed in #308 .

2022-04-08 05:15 UTC, aureate-labs-team commented
> can we rebased this I think there's too many unrelated changes to the topic.

Its because we've an open PR #308

2022-04-11 04:12 UTC, jeffpdotone approved these changes

2022-04-11 08:22 UTC, merged